

  - name: Install MariaDB package (CentOS)
    tags: centos, db, mariadb
    yum:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "CentOS"

  - name: Restart and enable MariaDB
    service:
      name: mariadb
      state: restarted
      enabled: true

  - name: Install MariaDB package (Ubuntu)
    tags: db, mariadb, ubuntu
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: Install Samba package
    tags: samba
    package:
      name: samba
      state: latest

  - name: Start httpd (CentOS)
    tags: apache, centos, httpd
    service:
      name: httpd
      state: started
    when: ansible_distribution == "CentOS"

  - name: Restart and enable MariaDB
    service:
      name: mariadb
      state: restarted
      enabled: true

  - name: Start httpd (CentOS)
    tags: centos, httpd
    service:
      name: httpd
      state: started
      enabled: true
